### PR TITLE
['FIX'] Console error : attempt to index a nil value (local 'player')

### PR DESCRIPTION
**Pull request by AnishBplayz**
[     script:ps-buffs] SCRIPT ERROR: @ps-buffs/server/main.lua:128: attempt to index a nil value (local 'player')
[     script:ps-buffs] > TriggerCallback (@qb-core/server/functions.lua:251)
[     script:ps-buffs] > handler (@qb-core/server/events.lua:152)

Attempt to fix this console error....

Tested and was fixed :)

Any suggestions are appreciated....

### CODE REVIEW

**Comment by xFutte** [comment]
To me, this seems to be more of a workaround to avoid getting an error message. Personally, I'd rather get an error message to identify where I have an error, if I forget to parse the source. I'd suggest to make a fallback that returns either a clever fallback or at least a message including the file name and why the print was printed.

**Comment by AnishBplayz** [comment]
Yeah this is a workaround for those who have no idea why even the error occurs but as it seems although the loop checks for player even when the player is not loaded in it throws this error or either when the player tries to logout it throws the error since the loop even then checks for the player so it is just a check to avoid throwing an error if the player not loded is not found.... (i.e) if the player is waiting in the character selection or tries to logout it throws this error

**Comment by MonkeyWhisper** [comment]
> Yeah this is a workaround for those who have no idea why even the error occurs but as it seems although the loop checks for player even when the player is not loaded in it throws this error or either when the player tries to logout it throws the error since the loop even then checks for the player so it is just a check to avoid throwing an error if the player not loded is not found.... (i.e) if the player is waiting in the character selection or tries to logout it throws this error

I know you explained a little above how it happens, but I tried it and I couldn't duplicate it.

Can you possible tell me please how to duplicate it? Step by step, I'll rather do a fix than a work around

**Comment by AnishBplayz** [comment]
> it.

**Comment by AnishBplayz** [comment]
This occurs when you try to logout using the /logout or logout in the apartment it would throw you a client side error stating the issue I mentioned above and it also appears on the server console too

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-buffs/issues/5

Let's attempt to fix it here

**Pull request closed without merging**
